github: [cqworker]
# patreon: cqworker
# open_collective: Open Collective username
# ko_fi:  Ko-fi username
# tidelift:Tidelift platform-name/package-name
# community_bridge: spring cloud
# liberapay: jdk
# issuehunt: cqworker
# otechie: Otechie username
custom:['www.juejin.im/', 'www.cn.bing.com/']
